### ISSUE TITLE
URL-escape hashes

### ISSUE THREAD

**Issue by klausbayrhammer** [pstenstrm/stylus-inline-svg#2]
When using the plugin to inline SVGs which contain color-codes with hashes, firefox cannot display them correctly. When inlining svgs without base64 encoding the inlined content should be url-encoded. Try the following [jsfiddle](http://jsfiddle.net/x9qp02y0/2/) with firefox and chrome to see the difference: 

Actual (containing `#`):

``` html
data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48"><path d="M0 48L48 0v48z" fill="#0b162f"/></svg>
```

Expected (`%23` instead of `#`):

``` html
data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48"><path d="M0 48L48 0v48z" fill="%230b162f"/></svg>
```

**Comment by pstenstrm** [comment]
The same problem will show up when targeting IDs: `fill="url(#linearGradient-1)"`.

It's of course safer to url-encode the entire SVG, but would that be necessary? Regular SVGs are supposedly url-safe...

I think encoding any `<` `>` `#` `&` and change double quotes `"` to single quotes `'` will do.

**Comment by klausbayrhammer** [comment]
For firefox I think it would be sufficient to just encode the `#`, but I'm not quite sure how IE handles data urls which are not fully url-encoded.

**Comment by klausbayrhammer** [comment]
Thanks for the fast fix! Works like a charm
